### ISSUE TITLE
Error on runing app.py 

### ISSUE THREAD

**Issue by HanzVivatma** [v-nhandt21/ViSV2TTS#8]
Chào bạn,
Rất cảm ơn vì chia sẻ project tuyệt vời này

T đã run app.py nhưng xảy ra lỗi. T thử sửa subprocess.check_call(Command, env=myenv, cwd=A) nhưng thất bại.
T  chạy trên win10 x64
Rất mong c gợi ý cách fix lỗi này.
Chờ hồi âm từ c. 

Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\Voice\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\ProgramData\miniconda3\envs\Voice\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\miniconda3\envs\Voice\lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "C:\ProgramData\miniconda3\envs\Voice\lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\miniconda3\envs\Voice\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ProgramData\miniconda3\envs\Voice\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\miniconda3\envs\Voice\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\ProgramData\miniconda3\envs\Voice\lib\site-packages\gradio\utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "C:/Colorizations/Voice/ViSV2TTS/app.py", line 98, in clonevoice
    outfile, text_norm = object.infer(text, speaker_source)
  File "C:/Colorizations/Voice/ViSV2TTS/app.py", line 63, in infer
    text_norm =TTSnorm(text)
  File "C:\ProgramData\miniconda3\envs\Voice\lib\site-packages\vinorm\__init__.py", line 28, in TTSnorm
    subprocess.check_call(Command, env=myenv, cwd=A)
  File "C:\ProgramData\miniconda3\envs\Voice\lib\subprocess.py", line 341, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\miniconda3\envs\Voice\lib\subprocess.py", line 859, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\miniconda3\envs\Voice\lib\subprocess.py", line 1328, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by Nghiauet** [comment]
Bạn dùng python version mấy

**Comment by doducthuan** [comment]
> Bạn dùng python version mấy

Tôi dùng python 3.11
